bookworm/dashboard/models.py
from .. import db
import datetime
import requests
from flask import current_app
import xmltodict
from ratelimit import limits, sleep_and_retry


class Note(db.Model):
    __tablename__ = 'NOTES'

    nid = db.Column('NID', db.Integer, primary_key=True)  # NoteID
    uid = db.Column('UID', db.Integer, db.ForeignKey('USERS.UID'), nullable=False)  # UserID
    bid = db.Column('BID', db.String(13), nullable=False)  # BookID
    note = db.Column('NoteText', db.String)  # Note text
    last_update = db.Column('LastUpdate', db.DateTime, nullable=False)  # Last updated

    def __init__(self, uid, bid):
        """
        Constructor to create a note instance in the database

        :param uid:
        :param bid:
        """
        self.uid = uid
        self.bid = bid

    def __repr__(self):
        return f'<Note {self.nid}>'

    def set_note(self, note):
        """
        Sets note body text

        :param note:
        :rtype: str
        """
        self.note = note

    def update_date(self):
        """
        Updates the last updated field
        """
        self.last_update = datetime.datetime.now()

    @staticmethod
    def get_note(uid, bid):
        """
        Returns note if exists or None if not

        :param uid:
        :param bid:
        """
        return Note.query.filter_by(uid=uid, bid=bid).first()

    @staticmethod
    def get_user_notes(uid):
        """
        Returns a list of tuples with ISBN codes

        :param uid:
        """
        return Note.query.filter_by(uid=uid).order_by(Note.last_update.desc()).all()


class APICall(object):
    def __init__(self, api_url, api_key):
        """
        Constructor for the APICall. Sets API URL and API key

        :param api_url:
        :param api_key:
        """
        self.api_url = api_url
        self.api_key = api_key
        self.last_request = datetime.datetime.now()
    
    def request(self, params=None):
        """
        Sends request and returns response, can set additional additional parameters by passing a dictionary

        :param params:
        :rtype: response object
        """
        params = params if params else dict()
        params['key'] = self.api_key
        try:
            response = requests.get(self.api_url, params=params)
        except requests.exceptions.RequestException as e:
            print(e)
            return None
        return response


class GoodReadsAPI(APICall):
    def __init__(self):
        """
        Creates a new instance of APICall by passing GoodReads API URL and key
        """
        super(GoodReadsAPI, self).__init__('https://www.goodreads.com/',
                                           current_app.config['GOODREADS_API_KEY'])
    
    def book_search(self, query):
        """
        Sends a book search request with a provided query. Returns a list of refactored
        dictionaries of found books.

        :param query:
        :rtype: list
        """
        self.api_url += 'search/index.xml'
        request = {'q': query}
        try:
            response = self.limited_request(request)
            if response.status_code == 401:
                raise InvalidApiKeyException("Provided API key is not valid")
        except (requests.exceptions.RequestException, InvalidApiKeyException) as e:
            print(e)
            return []
        parsed_response = XMLParser.to_dict(response.text)
        if parsed_response['GoodreadsResponse']['search']['total-results'] == '0':
            return []
        else:
            return self.__refactor_search_dict(parsed_response['GoodreadsResponse']['search']['results']['work'])

    def get_book(self, bid):
        """
        Sends a book request with a provided GoodReads BookID. Returns a dictionary containing
        information about the book

        :param bid:
        :return:
        """
        self.api_url += f'book/show/{bid}.xml'
        try:
            response = self.limited_request()
            if response.status_code == 401:
                raise InvalidApiKeyException("Provided API key is not valid")
        except (requests.exceptions.RequestException, InvalidApiKeyException) as e:
            print(e)
            return []
        return self.__refactor_book_dict(XMLParser.to_dict(response.text)['GoodreadsResponse']['book'])
    
    # Due to API rate limitations, only 1 request per sec is allowed
    @sleep_and_retry
    @limits(calls=1, period=1)
    def limited_request(self, params=None):
        return self.request(params)

    @staticmethod
    def __refactor_search_dict(books):
        result = []
        for book in books:
            book_info = dict()
            book_info['id'] = book['best_book']['id']['#text']
            book_info['title'] = book['best_book']['title']
            if '#text' in book['original_publication_year']:
                book_info['year'] = book['original_publication_year']['#text']
            else:
                book_info['year'] = 'Unknown Year'
            if type(book['best_book']['author']) is list:
                book_info['author'] = [author['name'] for author in book['best_book']['author']]
            else:
                book_info['author'] = [book['best_book']['author']['name']]
            book_info['img_url'] = book['best_book']['image_url']
            result.append(book_info)
        return result

    @staticmethod
    def __refactor_book_dict(book):
        book_info = dict()
        book_info['title'] = book['title']
        book_info['img_url'] = book['image_url']
        if type(book['authors']['author']) is list:
            book_info['author'] = [author['name'] for author in book['authors']['author']]
        else:
            book_info['author'] = [book['authors']['author']['name']]
        if 'publication_year' in book:
            book_info['year'] = book['publication_year']
        else:
            book_info['year'] = 'Unknown Year'

        book_info['isbn'] = book['isbn'] or book['isbn13']
        return book_info


class XMLParser(object):
    @staticmethod
    def to_dict(xml_string):
        """Converts the XML string into a dictionary using xmltodict module"""
        return xmltodict.parse(xml_string)


class InvalidApiKeyException(Exception):
    """Exception raised for invalid GoodReads API Key in config"""
    def __init__(self, message):
        self.message = '[GoodReadsAPI Error]: ' + message
        super().__init__(self.message)

bookworm/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, HiddenField, StringField
from wtforms.validators import DataRequired, Length, Email
from wtforms.fields.html5 import EmailField


class EditNote(FlaskForm):
    text = HiddenField("note", [DataRequired()])
    submit = SubmitField("Save")


class EditProfile(FlaskForm):
    first_name = StringField("First Name", [DataRequired(), Length(max=50)])
    last_name = StringField("Last Name", [DataRequired(), Length(max=50)])
    email = EmailField("Email", [DataRequired(), Email()])
    submit = SubmitField("Update")

bookworm/dashboard/__init__.py
def create_module(app):
    from .controllers import bp
    app.register_blueprint(bp)

bookworm/dashboard/controllers.py
from flask import Blueprint, render_template, redirect, url_for, g, request
from ..auth.controllers import login_required
from ..auth.models import User
from .models import db, Note, GoodReadsAPI
from .forms import EditNote, EditProfile
from sqlalchemy.orm.exc import NoResultFound

bp = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@bp.route('/')
@login_required
def dashboard():
    cards = []
    user_notes = Note.get_user_notes(g.user[0])
    for note in user_notes:
        card_info = GoodReadsAPI().get_book(note.bid)
        if len(card_info) == 0:
            continue
        card_info['last_update'] = note.last_update.strftime('%m/%d/%Y')
        card_info['bid'] = note.bid
        cards.append(card_info)
    return render_template('dashboard/dashboard.html', cards=cards)


@bp.route('/search')
@bp.route('/search/<query>')
@login_required
def book_search(query=None):
    if query:
        books = GoodReadsAPI().book_search(query)
        return render_template('dashboard/search.html', books=books, query=query)

    return render_template('dashboard/search.html', books=None, query=None)


@bp.route('/view/<bid>', methods=['GET', 'POST'])
@login_required
def note_view(bid):
    note = Note.get_note(g.user[0], bid)
    if note is None:
        return 'Note doesn\t exist'

    book = GoodReadsAPI().get_book(bid)
    return render_template('dashboard/view.html', book=book, note=note, bid=bid)


@bp.route('/edit/<bid>', methods=['GET', 'POST'])
@login_required
def note_edit(bid):
    note = Note.get_note(g.user[0], bid)
    if note is None:
        note = Note(g.user[0], bid)
        note.set_note('')
        note.update_date()
        db.session.add(note)
        db.session.commit()

    form = EditNote()
    if form.validate_on_submit():
        note.set_note(form.text.data)
        note.update_date()
        db.session.commit()
        return redirect(url_for('dashboard.note_view', bid=bid))
    book = GoodReadsAPI().get_book(bid)
    return render_template('dashboard/edit.html', book=book, form=form,
                           note=note, bid=bid)


@bp.route('/delete/<bid>')
@login_required
def note_delete(bid):
    note = Note.get_note(g.user[0], bid)
    if note is None:
        return '404'
    db.session.delete(note)
    db.session.commit()

    return redirect(url_for('dashboard.dashboard'))


@bp.route('/profile/', methods=['GET', 'POST'])
@bp.route('/profile/<int:uid>', methods=['GET', 'POST'])
@login_required
def profile(uid=None):
    if not uid:
        uid = g.user[0]

    user = User.query.get(uid)
    
    if not user:
        return redirect(url_for('main.index'))
    
    own_profile = False
    if uid == g.user[0]:
        own_profile = True

    form = EditProfile()
    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data
        db.session.commit()
        return redirect(url_for('dashboard.profile'))

    print(f'Accessed profile id: {uid}')
    return render_template('dashboard/profile.html', user=user, own_profile=own_profile, form=form)

bookworm/templates/dashboard/dashboard.html
{% extends 'layout.html' %}

{% block content %}
<section class="dashboard">
    <div class="dashboard-controls">
        <a href="{{ url_for('dashboard.book_search') }}" class="btn btn-new">Create New</a>
        <input type="text" name="Note search" placeholder="Search for your note" id="local-search">
    </div>
    <div class="dashboard-books">
      {% if cards[0] %}
        {% for card in cards %}
          <div class="card">
              <img src="{{ card['img_url'] }}">
              <h3 title="{{ card['title'] }}">{{ card['title'] }}</h3>
              <small title="by {{ card['author'] }}">by {{ card['author'][0] }}</small>
              <small>Last Edit: {{ card['last_update'] }}</small>
              <a class="btn btn-card" href="{{ url_for('dashboard.note_view', bid=card['bid']) }}">View</a>
          </div>
        {% endfor %}
      {% else %}
        <p>You don't have any notes.</p>
      {% endif %}
    </div>
</section>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='scripts.js') }}"></script>
{% endblock %}

bookworm/templates/dashboard/edit.html
{% extends 'layout.html' %}

{% block styles %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
{% endblock %}

{% block content %}
<section class="note-view">
  <div class="book-display">
    <img src="{{ book['img_url'] }}" alt="Book Cover">
    <div class="book-display-info">
      <h4>{{ book['title'] }}</h4>
      <small>by {{ book['author'] }}</small>
    </div>
    <div class="book-display-controls">
      <form method="post" id="form">
        {{ form.csrf_token() }}
        {{ form.text() }}
        {{ form.submit(class_="btn btn-green") }}
        <a href="{{ url_for('dashboard.note_delete', bid=bid) }}" class="btn btn-red">Delete note</a>
      </form>
    </div>
  </div>
  <div class="container note-body">
    <div id="editor-container">
    </div>
  </div>
</section>
{% endblock %}

{% block scripts %}
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
  var quill = new Quill('#editor-container', {
    modules: {
      toolbar: [
        ['bold', 'italic'],
        ['link', 'blockquote'],
        [{ list: 'ordered' }, { list: 'bullet' }]
      ]
    },
    placeholder: 'Compose an epic...',
    theme: 'snow'
  });
  quill.setContents({{ note.note|safe }});
  window.onload = function() {
    const form = document.getElementById('form');
    form.onsubmit = function() {
      const input = document.getElementById('text');
      input.value = JSON.stringify(quill.getContents());
    }
  }
</script>
{% endblock %}

bookworm/templates/dashboard/profile.html
{% extends 'layout.html' %}

{% block content %}
<section class="profile">
	<div class="profile-info">
		{% if own_profile %}
			<form method="post">
				{{ form.csrf_token() }}
				<div class="profile-item-edit">
					{{ form.first_name.label }}
					{{ form.first_name(value=user.first_name) }}
    				{% if form.first_name.errors %}
      					{% for e in form.first_name.errors %}
        					<small>{{ e }}</small>
      					{% endfor %}
    				{% endif %}
				</div>
				
				<div class="profile-item-edit">
	        		{{ form.last_name.label }}
					{{ form.last_name(value=user.last_name) }}
	        		{% if form.first_name.errors %}
	          			{% for e in form.last_name.errors %}
	            		<small>{{ e }}</small>
	          			{% endfor %}
	        		{% endif %}
	        	</div>

	        	<div class="profile-item-edit">
	        		{{ form.email.label }}
					{{ form.email(value=user.email) }}
	        		{% if form.email.errors %}
	          			{% for e in form.email.errors %}
	            		<small>{{ e }}</small>
	          			{% endfor %}
	        		{% endif %}
	        	</div>

        		{{ form.submit(class_="btn btn-auth") }}
			</form>
		{% else %}
			<div class="profile-item">
				<p class="profile-item-title">First Name:</p>
				<p class="profile-item-value">{{ user.first_name }}</p>
			</div>

			<div class="profile-item">
				<p class="profile-item-title">Last Name:</p>
				<p class="profile-item-value">{{ user.last_name}}</p>
			</div>

			<div class="profile-item">
				<p class="profile-item-title">Email:</p>
				<p class="profile-item-value">{{ user.email }}</p>
			</div>
		{% endif %}
	</div>
</section>
{% endblock %}

{% block scripts %}
{% endblock %}

bookworm/templates/dashboard/search.html
{% extends 'layout.html' %}

{% block content %}
<section class="dashboard">
    <div class="dashboard-controls">
        <input id="book-search" type="text" name="search" placeholder="Title, Author, ISBN..." {% if query %} value="{{query}}" {% endif %}>
        <a href="" class="btn btn-search" id="book-search-btn" onclick="search();">Search</a>
    </div>
    {% if books[0] %}
        <div class="search-results">
            {% for book in books %}
                <div class="search-result-card">
                    <img src="{{ book['img_url'] }}" alt="Book cover image">
                    <div class="searh-card-info">
                        <h3>{{ book['title'] }}</h3>
                        <small>Publication year: {{ book['year'] }}</small>
                        <small><i>by {% for author in book['author'] %} {{ author + ' ' }} {% endfor %}</i></small>
                    </div>
                    <a href="{{ url_for('dashboard.note_edit', bid=book['id']) }}" class="btn btn-choose">Choose</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No books found.</p>
    {% endif %}
</section>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='scripts.js') }}"></script>
{% endblock %}

bookworm/templates/dashboard/view.html
{% extends 'layout.html' %}

{% block styles %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
{% endblock %}

{% block content %}
<section class="note-view">
  <div class="book-display">
    <img src="{{ book['img_url'] }}" alt="Book Cover">
    <div class="book-display-info">
      <h4>{{ book['title'] }}</h4>
      <small>by {{ book['author'] }}</small>
    </div>
    <div class="book-display-controls">
      <a href="{{ url_for('dashboard.note_edit', bid=bid) }}" class="btn btn-red">Edit Note</a>
    </div>
  </div>
  <div class="container note-body">
    <div id="editor-container">
    </div>
  </div>
</section>
{% endblock %}

{% block scripts %}
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
  var options = {
  modules: {
    toolbar: false
  },
  placeholder: 'Compose an epic...',
  readOnly: true,
  theme: 'snow'
  };
  var editor = new Quill('#editor-container', options);
  editor.setContents({{ note.note|safe }});
  editor.disable();
</script>
{% endblock %}