bookworm/main/controllers.py
from flask import Blueprint, render_template

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    return render_template('main/index.html')


@bp.route('/about')
def about():
    return render_template('main/about.html')


@bp.errorhandler(404)
def page_not_found(e):
    print('asdasdasdasdasd')
    return render_template('404.html'), e

bookworm/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    {% block styles %}
    {% endblock %}
    <title>BookWorm</title>
  </head>
  <body>
    <!-- Navigation Bar -->
    <header>
        <h1 class="logo"><a href="{{ url_for('main.index') }}">BookWorm</a></h1>
        <nav>
            <ul>
                <li><a href="{{ url_for('dashboard.dashboard') }}">My Books</a></li>
                <li><a href="{{ url_for('main.about') }}">About</a></li>
            </ul>
        </nav>
        <div class="controls">
            {% if g.user %}
                <p>Hi, <a href="{{ url_for('dashboard.profile') }}">{{ g.user[1] }}</a></p>
                <a href="{{ url_for('auth.logout') }}" class="btn">Log Out</a>
            {% else %}
                <a href="{{ url_for('auth.login') }}" class="btn">Log In</a>
                <a href="{{ url_for('auth.register') }}" class="btn">Register</a>
            {% endif %}
        </div>
    </header>
    <!-- Navigation Bar End -->
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <!-- Scripts -->
    {% block scripts %}
    {% endblock %}

  </body>
</html>